import { CandidateProfile, JobPosting, ApplicationItem, ClientLead } from "./types";

export const initialCandidates: CandidateProfile[] = [
  {
    id: "cand-1",
    fullName: "Bhoomika K P",
    email: "bhoomika@example.com",
    phone: "+1 (555) 349-8201",
    location: "San Francisco, CA / Remote",
    linkedinUrl: "https://linkedin.com/in/bhoomika",
    githubUrl: "https://github.com/kpbhoomika",
    portfolioUrl: "https://bhoomika.dev",
    tier: "professional",
    targetRoles: ["Full Stack Engineer", "Frontend Architect", "AI Application Developer"],
    targetLocations: ["San Francisco, CA", "New York, NY", "Remote USA"],
    workModel: ["Remote", "Hybrid"],
    minSalary: 130000,
    currency: "USD",
    yearsOfExperience: 3,
    visaStatus: "US Citizen / Permanent Resident",
    noticePeriodDays: 14,
    blacklistedCompanies: ["Legacy Systems Corp"],
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Python",
      "PostgreSQL",
      "Tailwind CSS",
      "GraphQL",
      "Docker",
      "AWS",
      "Gemini API",
    ],
    masterResumeText: `Full Stack Engineer with 3+ years of experience engineering scalable web applications and AI-enabled platforms. Led frontend redesign at TechPulse increasing user engagement by 42%. Built microservices in Node.js & TypeScript handling 1M+ daily requests. Proficient in Next.js, React, Python, PostgreSQL, and modern cloud deployment.`,
    interviewsGuaranteed: 5,
    interviewsLanded: 3,
    applicationsSubmitted: 48,
    subscriptionActive: true,
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "cand-2",
    fullName: "Alex Chen",
    email: "alex.chen.grad@gmail.com",
    phone: "+1 (555) 782-9012",
    location: "Austin, TX / Remote",
    linkedinUrl: "https://linkedin.com/in/alex-chen-swe",
    githubUrl: "https://github.com/alexchen-dev",
    tier: "student",
    targetRoles: ["Junior Software Engineer", "Associate Backend Developer"],
    targetLocations: ["Austin, TX", "Remote USA"],
    workModel: ["Remote", "Hybrid", "On-site"],
    minSalary: 85000,
    currency: "USD",
    yearsOfExperience: 0,
    visaStatus: "F1 OPT / EAD",
    noticePeriodDays: 0,
    blacklistedCompanies: [],
    skills: ["Python", "Java", "React", "PostgreSQL", "Git", "REST APIs", "FastAPI"],
    masterResumeText: `Computer Science Graduate (Class of 2026) with strong foundation in data structures, algorithms, and full-stack development. Built an automated inventory management tool using Python & React for university labs. Completed 2 software engineering internships.`,
    interviewsGuaranteed: 5,
    interviewsLanded: 2,
    applicationsSubmitted: 32,
    subscriptionActive: true,
    createdAt: "2026-08-10T14:30:00Z",
  },
  {
    id: "cand-3",
    fullName: "Sarah Jenkins",
    email: "sarah.j.dev@outlook.com",
    phone: "+1 (555) 902-1144",
    location: "Seattle, WA / Remote",
    linkedinUrl: "https://linkedin.com/in/sarahjenkins-cloud",
    tier: "professional",
    targetRoles: ["Cloud DevOps Engineer", "Site Reliability Engineer", "Platform Engineer"],
    targetLocations: ["Seattle, WA", "Remote"],
    workModel: ["Remote"],
    minSalary: 155000,
    currency: "USD",
    yearsOfExperience: 5,
    visaStatus: "US Citizen",
    noticePeriodDays: 30,
    blacklistedCompanies: ["Amazon"],
    skills: ["Kubernetes", "Terraform", "AWS", "Go", "Python", "CI/CD", "Prometheus", "Linux"],
    masterResumeText: `Senior DevOps Engineer with 5 years managing multi-region AWS cloud infrastructure. Reduced cloud spend by 28% while improving 99.99% system uptime through automated Kubernetes cluster autoscaling and Terraform IaC pipelines.`,
    interviewsGuaranteed: 5,
    interviewsLanded: 4,
    applicationsSubmitted: 64,
    subscriptionActive: true,
    createdAt: "2026-07-20T08:15:00Z",
  },
];

export const initialJobs: JobPosting[] = [
  {
    id: "job-1",
    companyName: "Stripe",
    roleTitle: "Full Stack Engineer — Developer Platform",
    location: "San Francisco, CA (Remote Friendly)",
    workModel: "Remote",
    salaryRange: "$145,000 - $185,000 + Equity",
    atsPlatform: "Greenhouse",
    applyUrl: "https://boards.greenhouse.io/stripe/jobs/4829102",
    postedDate: "2026-08-18T08:00:00Z",
    description: `We are looking for a Full Stack Engineer to build developer-facing tools, APIs, and real-time dashboard interfaces. You will work closely with product and infrastructure teams using React, TypeScript, and Go/Node.js to deliver intuitive, high-performance financial developer experiences.`,
    requiredSkills: ["React", "TypeScript", "Node.js", "REST APIs", "PostgreSQL"],
    preferredSkills: ["GraphQL", "Next.js", "Docker", "FinTech Experience"],
    matchScore: 96,
  },
  {
    id: "job-2",
    companyName: "Linear",
    roleTitle: "Frontend Architect / Senior Product Engineer",
    location: "Remote (Global)",
    workModel: "Remote",
    salaryRange: "$150,000 - $190,000 + Equity",
    atsPlatform: "Ashby",
    applyUrl: "https://jobs.ashbyhq.com/linear/592019",
    postedDate: "2026-08-17T12:00:00Z",
    description: `Linear is looking for a product-minded Frontend Engineer to craft ultra-fast, delightful user workflows. Strong command of React state management, WebSockets, client-side caching, and modern web ergonomics required.`,
    requiredSkills: ["React", "TypeScript", "Tailwind CSS", "Next.js", "WebSockets"],
    preferredSkills: ["Design Systems", "Canvas API", "IndexedDB"],
    matchScore: 92,
  },
  {
    id: "job-3",
    companyName: "Vercel",
    roleTitle: "Software Engineer — AI Ecosystem",
    location: "Remote (USA)",
    workModel: "Remote",
    salaryRange: "$140,000 - $175,000",
    atsPlatform: "Greenhouse",
    applyUrl: "https://boards.greenhouse.io/vercel/jobs/512930",
    postedDate: "2026-08-18T15:30:00Z",
    description: `Join Vercel's AI Ecosystem team building Next.js AI integrations, streaming UI components, and generative workflows. Seeking engineers passionate about LLMs, modern JavaScript runtimes, and developer tooling.`,
    requiredSkills: ["Next.js", "TypeScript", "React", "Node.js", "Gemini API"],
    preferredSkills: ["Edge Runtime", "Python", "Vector Databases"],
    matchScore: 95,
  },
  {
    id: "job-4",
    companyName: "Datadog",
    roleTitle: "Associate Software Engineer (University / Fresher 2026)",
    location: "Austin, TX / New York, NY",
    workModel: "Hybrid",
    salaryRange: "$95,000 - $115,000",
    atsPlatform: "Lever",
    applyUrl: "https://jobs.lever.co/datadog/910283",
    postedDate: "2026-08-19T06:00:00Z",
    description: `Great opportunity for recent graduates and early-career software engineers. Work across telemetry pipelines, dashboards, and distributed systems using Go, Python, and React.`,
    requiredSkills: ["Python", "Java", "Data Structures", "Git", "REST APIs"],
    preferredSkills: ["Docker", "Linux", "React"],
    matchScore: 89,
  },
  {
    id: "job-5",
    companyName: "Retool",
    roleTitle: "Full Stack Engineer — Workflow Integrations",
    location: "San Francisco, CA / Hybrid",
    workModel: "Hybrid",
    salaryRange: "$140,000 - $180,000",
    atsPlatform: "Greenhouse",
    applyUrl: "https://boards.greenhouse.io/retool/jobs/381920",
    postedDate: "2026-08-18T18:00:00Z",
    description: `Build connective tissue for internal software. Strong understanding of backend database schemas, API orchestration, and intuitive frontend UI canvas editors.`,
    requiredSkills: ["TypeScript", "React", "PostgreSQL", "Node.js"],
    preferredSkills: ["GraphQL", "Redis", "Security/Auth"],
    matchScore: 91,
  },
];

export const initialApplications: ApplicationItem[] = [
  {
    id: "app-1",
    candidateId: "cand-1",
    jobId: "job-1",
    companyName: "Stripe",
    roleTitle: "Full Stack Engineer — Developer Platform",
    location: "San Francisco, CA (Remote Friendly)",
    status: "Interview Scheduled",
    appliedDate: "2026-08-05",
    atsPlatform: "Greenhouse",
    matchScore: 96,
    recruiterEmail: "recruiter.tech@stripe.com",
    outreachSent: true,
    interviewDate: "2026-08-22T15:00:00Z",
    notes: "Round 2 Technical Architecture screen scheduled with Engineering Manager.",
  },
  {
    id: "app-2",
    candidateId: "cand-1",
    jobId: "job-2",
    companyName: "Linear",
    roleTitle: "Frontend Architect",
    location: "Remote",
    status: "Screening",
    appliedDate: "2026-08-12",
    atsPlatform: "Ashby",
    matchScore: 92,
    recruiterEmail: "talent@linear.app",
    outreachSent: true,
    notes: "Recruiter phone screen scheduled for Thursday.",
  },
  {
    id: "app-3",
    candidateId: "cand-1",
    jobId: "job-3",
    companyName: "Vercel",
    roleTitle: "Software Engineer — AI Ecosystem",
    location: "Remote (USA)",
    status: "Interview Scheduled",
    appliedDate: "2026-08-08",
    atsPlatform: "Greenhouse",
    matchScore: 95,
    recruiterEmail: "careers@vercel.com",
    outreachSent: true,
    interviewDate: "2026-08-24T18:30:00Z",
    notes: "System Design & Live Coding session.",
  },
  {
    id: "app-4",
    candidateId: "cand-1",
    jobId: "job-5",
    companyName: "Retool",
    roleTitle: "Full Stack Engineer",
    location: "San Francisco, CA",
    status: "Offer Received",
    appliedDate: "2026-07-28",
    atsPlatform: "Greenhouse",
    matchScore: 91,
    recruiterEmail: "recruiting@retool.com",
    outreachSent: true,
    notes: "Official offer received: $165k Base + $40k Equity/yr. Ready for AI negotiation copilot.",
  },
  {
    id: "app-5",
    candidateId: "cand-1",
    jobId: "job-4",
    companyName: "Datadog",
    roleTitle: "Associate Software Engineer",
    location: "Austin, TX",
    status: "Applied",
    appliedDate: "2026-08-18",
    atsPlatform: "Lever",
    matchScore: 89,
    outreachSent: true,
    notes: "Application submitted via 1-click ATS dispatcher.",
  },
];

export const initialClientLeads: ClientLead[] = [
  {
    id: "lead-1",
    fullName: "David Kim",
    headline: "CS Graduate @ UT Austin | #OpenToWork | Seeking Junior Software Engineer Roles",
    targetRole: "Junior Full Stack / Backend Engineer",
    yearsOfExperience: 0,
    location: "Austin, TX / Remote",
    linkedinUrl: "https://linkedin.com/in/davidkim-swe-grad",
    source: "LinkedIn #OpenToWork",
    estimatedAtsScore: 68,
    missingSkills: ["Docker", "PostgreSQL", "CI/CD Pipelines", "FastAPI"],
    daysLooking: 45,
    status: "New Lead",
    suggestedTier: "student",
    notes: "Active poster. Posted 2 days ago about sending 180+ applications with 0 recruiter replies.",
  },
  {
    id: "lead-2",
    fullName: "Elena Rostova",
    headline: "Senior Distributed Systems Engineer | ex-CloudScale | #OpenToWork | Go, Kafka, AWS",
    targetRole: "Staff Backend Engineer / Platform Lead",
    yearsOfExperience: 6,
    location: "San Francisco, CA / Remote",
    linkedinUrl: "https://linkedin.com/in/elena-rostova-tech",
    source: "Layoff Post (#OpenToWork)",
    estimatedAtsScore: 74,
    missingSkills: ["Kubernetes", "gRPC Architecture", "p99 Metric Realignment"],
    daysLooking: 60,
    status: "Audit Sent",
    suggestedTier: "professional",
    notes: "Laid off in company restructuring. High willingness to pay $99 for direct VP/Director outreach.",
  },
  {
    id: "lead-3",
    fullName: "Michael Zhang",
    headline: "Frontend Developer (React, Next.js, TypeScript) | #OpenToWork | 2 YOE",
    targetRole: "Mid-Level Frontend / Product Engineer",
    yearsOfExperience: 2,
    location: "New York, NY / Remote",
    linkedinUrl: "https://linkedin.com/in/michaelzhang-frontend",
    source: "Google X-Ray Search",
    estimatedAtsScore: 72,
    missingSkills: ["GraphQL", "Tailwind CSS", "Jest / Testing Library"],
    daysLooking: 30,
    status: "DM Sent",
    suggestedTier: "professional",
    notes: "Sent 3-sentence DM with free ATS score preview.",
  },
  {
    id: "lead-4",
    fullName: "Ananya Patel",
    headline: "Cloud & DevOps Engineer | AWS Certified Solutions Architect | #OpenToWork",
    targetRole: "Senior Site Reliability / DevOps Engineer",
    yearsOfExperience: 4,
    location: "Chicago, IL / Remote",
    linkedinUrl: "https://linkedin.com/in/ananya-patel-cloud",
    source: "LinkedIn #OpenToWork",
    estimatedAtsScore: 76,
    missingSkills: ["Terraform", "Prometheus/Grafana", "Helm Charts"],
    daysLooking: 20,
    status: "Converted ($99)",
    suggestedTier: "professional",
    notes: "Enrolled in $99 Pro Plan! Guaranteed 5 interviews active.",
  },
  {
    id: "lead-5",
    fullName: "James Wilson",
    headline: "Entry-Level Python Developer | BootCamp Grad 2026 | #OpenToWork",
    targetRole: "Junior Backend Developer",
    yearsOfExperience: 1,
    location: "Remote (USA)",
    linkedinUrl: "https://linkedin.com/in/james-wilson-python",
    source: "LinkedIn #OpenToWork",
    estimatedAtsScore: 62,
    missingSkills: ["REST APIs", "SQL Optimization", "Docker"],
    daysLooking: 90,
    status: "New Lead",
    suggestedTier: "student",
    notes: "Frustrated with job boards. Prime candidate for $20 student/fresher plan.",
  },
];
